# Author  : myapit
# Date    : October 2025
# Purpose : Template to deploy container with nginx + php-fpm 8 + mariadb
#
#
name: mywebserver
services:
  nginx:
    image: nginx:alpine
      #container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./myapp:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - myapp-network

  php:
    image: php:8.4-fpm
      #container_name: php-fpm
    volumes:
      - ./myapp:/var/www/html
    networks:
      - myapp-network

  mysql:
    image: mariadb:latest
      #container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: myapp_password
    volumes:
      - ./mysql-data:/var/lib/mysql
        #- mysql-data:/var/lib/mysql #--USE THIS IF WANT TO USER DOCKER VOLUME
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge

# ENABLE WHEN USE DOCKER VOLUME      
#volumes:
#  mysql-data:
